# Schema for the configuration files of the auto_title module.

auto_title.node.*:
  type: mapping
  label: 'The auto title settings'
  mapping:
    status:
      type: integer
      label: 'Preview before submitting'
    php:
      type: integer
      label: 'The auto title php settings'
    pattern:
      type: string
      label: 'The auto title pattern settings'

action.configuration.auto_title_update_action:
  type: action_configuration_default
  label: 'Update automatic titles'